markdown: kramdown
highlighter: rouge  #pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: pythoncharles
author: "王成龙"
email: 1054452533@qq.com
name: "王成龙个人博客"
url: https://charles.weii.ink/
domain: charles.weii.ink/
all_categories: [
["python", "Python开发","/posts/python.html"],
["web", "Web框架","/posts/web.html"],
["linux", "Linux相关","/posts/linux.html"],
["internet", "网络","/posts/internet.html"],
["database", "数据库","/posts/database.html"],
["algorithm", "算法","/posts/algorithm.html"],
["read", "读书笔记","/posts/read.html"],
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
- jekyll-paginate
